include:
  - path:
      - ../compose.yml

services:
  # Visualizes the telemetry data
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:10.4.2
    restart: unless-stopped
    user: '0'
    ports: # Can be removed if using Traefik
      - 3000:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch correlations traceQLStreaming metricsSummary traceqlEditor
    volumes:
      - '/var/lib/model-runner/grafana:/var/lib/grafana'
      - '../telemetry/config/grafana/grafana.ini:/etc/grafana/grafana.ini'
      - '../telemetry/config/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml'
      - '../telemetry/config/grafana/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'
      - '../telemetry/config/grafana/dashboards:/var/lib/grafana/dashboards'
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`) || PathPrefix(`/grafana`)"
    networks:
      - mesh

  # Collects telemetry data
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.99.0
    restart: unless-stopped
    volumes:
      - ../telemetry/config/otel/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"

  # Stores metrics
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    command:
      - "--enable-feature=otlp-write-receiver" # Native OpenTelemetry HTTP receiver
    volumes:
      - ../telemetry/config/prometheus/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"

  # Stores traces
  tempo:
    container_name: tempo
    image: grafana/tempo:2.4.1
    user: '0'
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../telemetry/config/tempo/tempo.yaml:/etc/tempo.yaml
      - /var/lib/model-runner/tempo:/var/tempo
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"
