include:
  - path:
      - ../compose.yml

services:
  # Visualizes the telemetry data
  grafana: # todo auto setup datasources and dashboards
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - '/var/lib/model-runner/grafana:/var/lib/grafana'
      - '../telemetry/grafana.ini:/etc/grafana/grafana.ini'
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`) || PathPrefix(`/grafana`)"
    networks:
      - mesh

  # Collects telemetry data
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: unless-stopped
    volumes:
      - ../telemetry/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"

  # Stores metrics
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    command:
      - "--enable-feature=otlp-write-receiver" # Native OpenTelemetry HTTP receiver
    volumes:
      - ../telemetry/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"

  # Stores logs
  loki: # todo
    container_name: loki
    image: grafana/loki
    restart: unless-stopped
    volumes:
      - ../telemetry/loki.yaml:/etc/loki/local-config.yaml
      - /var/lib/model-runner/loki:/loki
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"

  # Stores traces
  tempo:
    container_name: tempo
    image: grafana/tempo
    user: '0'
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../telemetry/tempo.yaml:/etc/tempo.yaml
      - /var/lib/model-runner/tempo:/var/tempo
    networks:
      - mesh
    labels:
      - "com.centurylinklabs.watchtower.scope=modelrunner"
