include:
  - path:
      - ../compose.yml

services:
  grafana: # todo auto setup datasources and dashboards
    container_name: grafana
    image: grafana/grafana-oss
    restart: unless-stopped
    user: '0'
    ports:
      - '3000:3000'
    volumes:
      - '/var/lib/model-runner/grafana:/var/lib/grafana'
      - '../telemetry/grafana.ini:/etc/grafana/grafana.ini'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`) || PathPrefix(`/grafana`)"
    networks:
      - mesh

  otel-collector: # Not expected to be access externally, so no traefik labels.
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: unless-stopped
    ports:
      - 4317:4317 # OTLP gRPC receiver endpoint
    volumes:
      - ../telemetry/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - mesh

  prometheus: # Not expected to be access externally, so no traefik labels
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    command:
      - "--enable-feature=otlp-write-receiver" # Native OpenTelemetry HTTP receiver
    ports:
      - 9090:9090
    volumes:
      - ../telemetry/prometheus.yml:/prometheus/prometheus.yml
    networks:
      - mesh

  loki: # Not expected to be access externally, so no traefik labels
    container_name: loki
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ../telemetry/loki.yaml:/etc/loki/local-config.yaml
      - /var/lib/model-runner/loki:/loki
    networks:
      - mesh
