version: "3.9"
name: model_runner_service

services:
  model_runner:
    # Find other image types under: https://github.com/frkri/ModelRunner/pkgs/container/modelrunner
    image: ghcr.io/frkri/modelrunner:latest
    container_name: model_runner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "25566:25566"
    healthcheck:
      test: [
          "CMD",
          "/ModelRunner/model_runner_health",
          "http://localhost:25566/health", # Make sure to change the port and protocol (https / http) to match your setup
        ]
      start_period: 10s
      interval: 60s
      timeout: 15s
      retries: 4
    environment:
      - RUST_LOG=info
      - SQLITE_FILE_PATH=/ModelRunner/db/model_runner.db
      - HF_HOME=/ModelRunner/hf-cache
      - ADDRESS=0.0.0.0
      - PORT=25566
      # - CONFIG_FILE=/ModelRunner/ModelRunner.toml
      # - CERTIFICATE=/run/secrets/cert-file
      # - PRIVATE_KEY=/run/secrets/key-file
    volumes:
      - /var/cache/hf-cache:/ModelRunner/hf-cache # Cache dir for the downloaded files (models and other files) from Hugging Face, to be used with the HF_HOME environment variable
      - /var/lib/model-runner:/ModelRunner/db # Database dir for the SQLite database file, to be used with the SQLITE_FILE_PATH environment variable
    # configs:
    #  - source: model_runner_config
    #    target: /ModelRunner/ModelRunner.toml
    # secrets:
    #  - cert-file
    #  - key-file

# Use the following to mount the config file rather than using environment variables. See https://docs.docker.com/compose/compose-file/08-configs/
configs:
  model_runner_config:
    file: ./ModelRunner.toml.example

secrets:
  cert-file:
    file: ./path/to/your/cert.file
  key-file:
    file: ./path/to/your/key.file
