receivers:
  otlp:
    protocols:
      grpc:

  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 15s
          static_configs:
            - targets: ["otel-collector:8888"]
        - job_name: "prometheus"
          scrape_interval: 15s
          static_configs:
            - targets: ["prometheus:9090"]
        - job_name: "loki"
          scrape_interval: 15s
          static_configs:
            - targets: ["loki:3100"]
        - job_name: "tempo"
          scrape_interval: 15s
          static_configs:
            - targets: ["tempo:3200"]

processors:
  batch:

exporters:
  otlphttp/metrics: # Native OTLP export over HTTP
    endpoint: "http://prometheus:9090"
    metrics_endpoint: "http://prometheus:9090/api/v1/otlp/v1/metrics"

  loki/logs:
    endpoint: "http://loki:3100/loki/api/v1/push"

  otlp/traces:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  # Debug log
  logging:
    loglevel: debug

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki/logs]
    metrics:
      receivers:
        - otlp
        - prometheus
      processors: [batch]
      exporters: [otlphttp/metrics]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
