apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    version: 1
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    uid: tempo
    orgId: 1
    url: http://tempo:3200
    version: 1
    editable: false
