### See status of an API key. JSON body with target ID is optional
POST http://{{host}}:{{port}}/auth/status
content-type: application/json
authorization: Bearer {{api_key}}

{
  "id": "{{api_id}}"
}

### Create an new API key with permissions
POST http://{{host}}:{{port}}/auth/create
content-type: application/json
authorization: Bearer {{api_key}}

{
  "name": "new_api_key",
  "permissions": [
    "UseSelf",
    "StatusSelf",
    "CreateSelf",
    "UpdateSelf",
    "DeleteSelf"
  ]
}

### Delete an API key
POST http://{{host}}:{{port}}/auth/delete
content-type: application/json
authorization: Bearer {{api_key}}

{
  "id": "{{api_id}}"
}

### Update an API key
POST http://{{host}}:{{port}}/auth/update
content-type: application/json
authorization: Bearer {{api_key}}

{
  "id": "{{api_id}}",
  "name": "updated_key",
  "permissions": ["UseSelf", "StatusSelf", "CreateSelf", "UpdateSelf", "DeleteSelf"]
}
