POST http://localhost:25566/text/instruct
content-type: application/json

{
  "model": "phi2",
  "input": "Give me in percent how likely is this email to be a phishing email. The email title is 'You have won a prize! Click here to claim it!'. What is the probability that this email is a phishing email?",
  "max_length": 100
}

### Mistral 7B
POST http://localhost:25566/text/instruct
content-type: application/json

{
  "model": "mistral7b",
  "input": "Give me in percent how likely is this email to be a phishing email. The email title is 'You have won a prize! Click here to claim it!'. What is the probability that this email is a phishing email?.",
  "max_length": 100
}

### StableLM 2 Zephyr 1.6B
POST http://localhost:25566/text/instruct
content-type: application/json

{
  "model": "stablelm2",
  "input": "Give me in percent how likely is this email to be a phishing email. The email title is 'You have won a prize! Click here to claim it!'. What is the probability that this email is a phishing email?.",
  "max_length": 100
}