### Phi 2
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "phi2",
  "input": "USER: Give me a detailed report about tomorrows sunny weather. ASSISTANT:",
  "max_length": 150,
  "model_config": {
    "temperature": 0.6,
    "seed": 12345,
    "top_p": 0.2,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}

### Phi 3
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "phi3",
  "input": "<|system|>You are a helpful meteorologist.\n<|end|>\n<|user|>\nGive me a detailed report about tomorrows sunny weather.<|end|>\n<|assistant|>\n",
  "max_length": 150,
  "model_config": {
    "temperature": 0.6,
    "seed": 12345,
    "top_p": 0.6,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}


### Mistral 7B Instruct
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "mistral7b",
  "input": "<s>[INST] Give me a detailed report about tomorrows sunny weather. [/INST]",
  "max_length": 150,
  "model_config": {
    "temperature": 0.2,
    "seed": 12345,
    "top_p": 0.6,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}

### OpenHermes 2.5 Mistral7B
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "openhermes",
  "input": "<|im_start|>user\nGive me a detailed report about tomorrows sunny weather.<|im_end|>\n<|im_start|>assistant\n",
  "max_length": 150,
  "model_config": {
    "temperature": 0.2,
    "seed": 12345,
    "top_p": 0.6,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}

### StableLM 2 1.6B
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "stablelm2",
  "input": "<|user|>\nGive me a detailed report about tomorrows sunny weather.<|endoftext|>\n<|assistant|>\n",
  "max_length": 150,
  "model_config": {
    "temperature": 0.6,
    "seed": 12345,
    "top_p": 0.6,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}

### StableLM 2 Zephyr 1.6B
POST http://{{host}}:{{port}}/text/raw
content-type: application/json
authorization: Bearer {{api_key}}

{
  "model": "stablelm2",
  "input": "Give me a detailed report about tomorrows sunny weather.",
  "max_length": 150,
  "model_config": {
    "temperature": 0.6,
    "seed": 12345,
    "top_p": 0.6,
    "repeat_penalty": 1.1,
    "repeat_context_size": 64
  }
}
