POST http://localhost:25566/audio/transcribe
Content-Type: multipart/form-data; boundary=bounds

--bounds
Content-Disposition: form-data; name="request_content"
Content-Type: application/json

{"model": "whisper", "language": "en"}
--bounds
Content-Disposition: form-data; name="audio_content" filename="wavfile.wav"
Content-Type: audio/wav

< ./samples_jfk.wav
--bounds--

