include:
  - path:
      - ../compose.yml

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: /run/secrets/tunnel-token
    secrets:
      - tunnel-token
    networks:
      - mesh

secrets:
  tunnel-token:
    file: tunnel-secret.txt
